version: '3.3'

services:
  postgres:
    image: postgres:15.1
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5420:5432"
    volumes:
      - $HOME/docker/volumes/serv-my-codes/postgres:/var/lib/postgresql/data
